version: "2"
services:
  apache:
    image: eeacms/apache
    ports:
    - "80:80"
    depends_on:
    - plone
    environment:
      SERVER_ADMIN: "helpdesk@plone.dev"
      SERVER_NAME: "plone.dev"
      RewriteRule: "^/(.*) http://plone:8080/VirtualHostBase/http/plone.dev:80/VirtualHostRoot/$$1 [P,L]"
  plone:
    image: plone
